### ISSUE TITLE
Incorrect maximum batch size 

### ISSUE THREAD

**Issue by showered** [kin-labs/mogami#189]
Please change the `>=` operator to `>`

https://github.com/kin-labs/mogami/blob/e74755fdad55b5e186a063299b80483c9306d203/libs/sdk/src/lib/helpers/serialize-make-transfer-batch-transactions.ts#L27

**Comment by beeman** [comment]
Thanks for reporting this issue @showered - this has now been released as v1.0.0-beta.6.
