### ISSUE TITLE
BUG: Successful response even when payment failed

### ISSUE THREAD

**Issue by showered** [kin-labs/mogami#197]
**The issue:**

On `mainnet` I received a `"Succeed"` response when using `makeTransferBatch`, but actually the payment didn't go through.

``` 
data: {
    id: 'cl3dn3mlk344080u5jf6w40yy',
    createdAt: '2022-05-19T23:24:13.736Z',
    updatedAt: '2022-05-19T23:24:13.798Z',
    amount: 2500000,
    destination: 'CkHVJKp2XUNeT8TNvQPK5KZ77wTtLCRCvCzyy4gCPXM2',
    errors: [],
    feePayer: 'PEERY2i4UHUVjKhBSAphGpp3N6Vzv6aoCNKHJnBRSWA',
    mint: 'kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6',
    source: 'BUS5SyrVLhgakivdRcmZE5F69HdR8xJBjHTiF2mqdKpt',
    signature: '4xGaNkc2qeYE27hTndZ1MEUCBzNaBJKEB6aryKbde3vTJ1NFnNKZDPkmNeCSomykJ4KejopX7mdhnbUz9rqz9o3B',
    solanaStart: '2022-05-19T23:24:13.765Z',
    solanaEnd: '2022-05-19T23:24:13.796Z',
    status: 'Succeed',
    webhookEventStart: null,
    webhookEventEnd: null,
    webhookVerifyStart: null,
    webhookVerifyEnd: null,
    appId: 'cl3djh8ca012080u50x9im0xj'
  }
```

**The solution:**

I'm sure it goes without saying but `status` should be correct 100% of the time. I don't know what caused the above scenario, perhaps it was Bad Nonce?

**Comment by RamirezAlex** [comment]
Thanks @showered for reporting the bug. I will take a look at it.

**Comment by showered** [comment]
Yeah it's ok I know it's not ready for production just yet, I'm just getting in there early so I can hopefully assist with bug reporting and feature suggestions!

Sounds like this is being fixed in #179 ?

**Comment by RamirezAlex** [comment]
@showered I have being trying to reproduce the issue and so far, status seems to be correct in my end. I will keep digging, but in the meantime if you have any ideas on how to reproduce it, I'll appreciate it. Thank you.

**Comment by showered** [comment]
`makeTransferBatch()` on `mainnet` fails for me every time.

You can see below that each request is successful, and it returns a signature. But if you try and look them up on Solana Explorer they don't exist.

```
Tx time: 831
successfully sent batch in 0.83 seconds (txId: 34w5WgoJD3p6cZzQfZ8R1JLhXJAvcQLewymBa2CMJ97nVFjZ4NvBAtZQmPVRTKoJZfS4uNG5QBGanavDnheVF7WF)
Done. 2
Tx time: 951
successfully sent batch in 0.95 seconds (txId: 2s55BzcuSCeRpWxn6dEpmzovEBWZvGdyHeQPEJu8nCgEZWM3R1jfjdLhPH2S4UTKHyiMrVzUpqFe5TxD7YJP4etL)
Done. 2
Tx time: 901
successfully sent batch in 0.90 seconds (txId: 5pd83aptzKb2m1VGGdkaXteK3b6e3q9zrJqNvQAPxjHpsCDzovFrVWFuJ4GHoF73gdaKrgvsZYo9ez9kCfGyknYM)
Done. 2
Tx time: 963
successfully sent batch in 0.96 seconds (txId: 5vAjLuFYiA6zm44pPvLbyksxEaVVhJuEsnsYFrqo45bfYqFyDXWbNKwDt7MT3aqzimGrMwZz5HBFin1Nkvq8GG2g)
Done. 2
Tx time: 950
successfully sent batch in 0.95 seconds (txId: 2jTvSKSZ4VbzSVCaLM1UqEbSynNxbds9pxgTVvzhgyUXjT6XgJZ3f63jSm9qJaw47TQyd66Ho5vP6gAA77gPYuom)
Done. 2
Tx time: 965
successfully sent batch in 0.96 seconds (txId: 5iNw6nQ2QahmR2V7KTYTqYFEzUTJ1EaujwKo5bLrwciuP5sRpJQCxpM8pTv3xU8N2nGgrJunp2793ZvueyuYrGs7)
Done. 2
```

**Comment by beeman** [comment]
> `makeTransferBatch()` on `mainnet` fails for me every time.
> 
> You can see below that each request is successful, and it returns a signature. But if you try and look them up on Solana Explorer they don't exist.
> 
> ```
> Tx time: 831
> successfully sent batch in 0.83 seconds (txId: 34w5WgoJD3p6cZzQfZ8R1JLhXJAvcQLewymBa2CMJ97nVFjZ4NvBAtZQmPVRTKoJZfS4uNG5QBGanavDnheVF7WF)
> Done. 2
> Tx time: 951
> successfully sent batch in 0.95 seconds (txId: 2s55BzcuSCeRpWxn6dEpmzovEBWZvGdyHeQPEJu8nCgEZWM3R1jfjdLhPH2S4UTKHyiMrVzUpqFe5TxD7YJP4etL)
> Done. 2
> Tx time: 901
> successfully sent batch in 0.90 seconds (txId: 5pd83aptzKb2m1VGGdkaXteK3b6e3q9zrJqNvQAPxjHpsCDzovFrVWFuJ4GHoF73gdaKrgvsZYo9ez9kCfGyknYM)
> Done. 2
> Tx time: 963
> successfully sent batch in 0.96 seconds (txId: 5vAjLuFYiA6zm44pPvLbyksxEaVVhJuEsnsYFrqo45bfYqFyDXWbNKwDt7MT3aqzimGrMwZz5HBFin1Nkvq8GG2g)
> Done. 2
> Tx time: 950
> successfully sent batch in 0.95 seconds (txId: 2jTvSKSZ4VbzSVCaLM1UqEbSynNxbds9pxgTVvzhgyUXjT6XgJZ3f63jSm9qJaw47TQyd66Ho5vP6gAA77gPYuom)
> Done. 2
> Tx time: 965
> successfully sent batch in 0.96 seconds (txId: 5iNw6nQ2QahmR2V7KTYTqYFEzUTJ1EaujwKo5bLrwciuP5sRpJQCxpM8pTv3xU8N2nGgrJunp2793ZvueyuYrGs7)
> Done. 2
> ```

Thanks. We will do some proper testing on mainnet this week.

**Comment by RamirezAlex** [comment]
> `makeTransferBatch()` on `mainnet` fails for me every time.
> 
> You can see below that each request is successful, and it returns a signature. But if you try and look them up on Solana Explorer they don't exist.
> 
> ```
> Tx time: 831
> successfully sent batch in 0.83 seconds (txId: 34w5WgoJD3p6cZzQfZ8R1JLhXJAvcQLewymBa2CMJ97nVFjZ4NvBAtZQmPVRTKoJZfS4uNG5QBGanavDnheVF7WF)
> Done. 2
> Tx time: 951
> successfully sent batch in 0.95 seconds (txId: 2s55BzcuSCeRpWxn6dEpmzovEBWZvGdyHeQPEJu8nCgEZWM3R1jfjdLhPH2S4UTKHyiMrVzUpqFe5TxD7YJP4etL)
> Done. 2
> Tx time: 901
> successfully sent batch in 0.90 seconds (txId: 5pd83aptzKb2m1VGGdkaXteK3b6e3q9zrJqNvQAPxjHpsCDzovFrVWFuJ4GHoF73gdaKrgvsZYo9ez9kCfGyknYM)
> Done. 2
> Tx time: 963
> successfully sent batch in 0.96 seconds (txId: 5vAjLuFYiA6zm44pPvLbyksxEaVVhJuEsnsYFrqo45bfYqFyDXWbNKwDt7MT3aqzimGrMwZz5HBFin1Nkvq8GG2g)
> Done. 2
> Tx time: 950
> successfully sent batch in 0.95 seconds (txId: 2jTvSKSZ4VbzSVCaLM1UqEbSynNxbds9pxgTVvzhgyUXjT6XgJZ3f63jSm9qJaw47TQyd66Ho5vP6gAA77gPYuom)
> Done. 2
> Tx time: 965
> successfully sent batch in 0.96 seconds (txId: 5iNw6nQ2QahmR2V7KTYTqYFEzUTJ1EaujwKo5bLrwciuP5sRpJQCxpM8pTv3xU8N2nGgrJunp2793ZvueyuYrGs7)
> Done. 2
> ```

Thanks for providing context, as @beeman mentioned, we will do proper testing this week. However, I can see all the transactions you reported on Solana Explorer.

1. https://explorer.solana.com/tx/34w5WgoJD3p6cZzQfZ8R1JLhXJAvcQLewymBa2CMJ97nVFjZ4NvBAtZQmPVRTKoJZfS4uNG5QBGanavDnheVF7WF

2. https://explorer.solana.com/tx/2s55BzcuSCeRpWxn6dEpmzovEBWZvGdyHeQPEJu8nCgEZWM3R1jfjdLhPH2S4UTKHyiMrVzUpqFe5TxD7YJP4etL

3. https://explorer.solana.com/tx/5pd83aptzKb2m1VGGdkaXteK3b6e3q9zrJqNvQAPxjHpsCDzovFrVWFuJ4GHoF73gdaKrgvsZYo9ez9kCfGyknYM

4. https://explorer.solana.com/tx/5vAjLuFYiA6zm44pPvLbyksxEaVVhJuEsnsYFrqo45bfYqFyDXWbNKwDt7MT3aqzimGrMwZz5HBFin1Nkvq8GG2g

5. https://explorer.solana.com/tx/2jTvSKSZ4VbzSVCaLM1UqEbSynNxbds9pxgTVvzhgyUXjT6XgJZ3f63jSm9qJaw47TQyd66Ho5vP6gAA77gPYuom

6. https://explorer.solana.com/tx/5iNw6nQ2QahmR2V7KTYTqYFEzUTJ1EaujwKo5bLrwciuP5sRpJQCxpM8pTv3xU8N2nGgrJunp2793ZvueyuYrGs7

I wonder if there was a temporary issue with the Explorer or that we are returning the transaction as successful when it is `COMPLETED` instead of `FINALIZED`.  Anyways, thank you again for reporting it. We will look at it. :)

**Comment by showered** [comment]
Wow you're right! Also I just did another test (x10) and they all worked (see below).

However, as per the original comment on this issue, it **did** fail once. And if it fails once, it'll fail again. So it's something to keep an eye on.

```
Tx time: 1069
successfully sent batch in 1.07 seconds (txId: 2R7zpD5Ws2MGK2nd7Qg6iUiGrCgYCYieN9So7kxSHNxU6DxFo4cwJynDrJqeBvT2HorBmHikjaNshBktzDHKXjNN)
Done. 15
Tx time: 1024
successfully sent batch in 1.02 seconds (txId: 2HphTp1CVxHsycv4TK6xxdAJUCCJ15NU2xBYYS68VpJ13tvGe277rLP3GRGsS6e7qJh8B32S8iLLGs76TWt356Lk)
Done. 15
Tx time: 840
successfully sent batch in 0.84 seconds (txId: 3K7A5JHKhYUcJLBtvg2j9KiLSd9tdUpBYPheLHAZjXmr4jtYPjiGfcXt46hWTnLP1M1DcownmqNoe12kBcD2DCH)
Done. 15
Tx time: 953
successfully sent batch in 0.95 seconds (txId: 3q73s1LSkm1MKTWk5s1ArJhDRiCuHM3YDRS2x7fovxnz398MEnBnPbdATr2pTaBbhX8HoxZZsDL5X2Kq9ctRh1pA)
Done. 15
Tx time: 953
successfully sent batch in 0.95 seconds (txId: 2o5cEUtuzmFoPU9wpkSUdMZ2H7yYSkszpBLKu6vSQrnmkFtYHGwXpiDD6zUNiuSNb9ZGk1SxnkudNwruRKuXgNYP)
Done. 15
Tx time: 957
successfully sent batch in 0.96 seconds (txId: 4dUszsjdTc4pD2PRn3pJzK2KJTLkf3Fj3qwEsMRH3PEBni1QjqHpwdkn1NTsc4jxajziUD8G528Z7KYXVJmzLqTa)
Done. 15
Tx time: 984
successfully sent batch in 0.98 seconds (txId: 25AhvwvKTonDv5JLN5cnpPQzJkpTV2FmHuzgVU2S4Zv6z9rxah7THXfQ8jFFkEYNQCwq5aPzWJ2WsexUYTpgKyoZ)
Done. 15
Tx time: 868
successfully sent batch in 0.87 seconds (txId: 2DeAPpvKvmK7JyMtjvLzzmizbSAfQiaBwBAwpt59g1AAbMfKUjXjGZjX3BhWCsVM8eAhTLafpL3T4nZ6Mgi8bgsT)
Done. 15
Tx time: 1093
successfully sent batch in 1.09 seconds (txId: 2DeAPpvKvmK7JyMtjvLzzmizbSAfQiaBwBAwpt59g1AAbMfKUjXjGZjX3BhWCsVM8eAhTLafpL3T4nZ6Mgi8bgsT)
Done. 15
Tx time: 967
successfully sent batch in 0.97 seconds (txId: 5y7QmefJvfTG4bas2LUwJ1NfP8npAjYzQvddZ41sMiFKxAmjSPwwiKj3GNnoZRsBq3FD2f91tTEG4mzVBLXiEUcw)
Done. 15
```
