### ISSUE TITLE
Suggestion: Batch payment error index

### ISSUE THREAD

**Issue by showered** [kin-labs/mogami#201]
**The issue:**

If you try to send a batch payment to 10 accounts, but the 8th account in the array doesn't exist, you receive the following error:

```
  errors: [
    'Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 8: invalid account data for instruction'
  ],
```

The SDK/API correctly identifies that the 8th payment is trying to send to an account that doesn't exist. However, on the client, we need a better way to handle this. We need to know which payment is problematic so we can resolve the issue.

**The solution:**

Perhaps it would be good if each error was an object. Something like this:

```
  errors: [
    {
      fullDescription: 'Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 8: invalid account data for instruction',
      type: 'DestinationDoesNotExist',
      paymentIndex: 7,
    },
  ],
```

**Comment by RamirezAlex** [comment]
I'll care of this.
